### PR TITLE
Feat fix esp if def

### LINKED ISSUE #209: Add #ifdefs for ESP32
Remove any unnecessary #ifdefs for M0

### PR DESCRIPTION
**Pull request by produceconsumerobot**
Cleaned up #ifdef to make code more maintainable and extensible

- closes #209
- Moved outstanding items to #225

### CODE REVIEW

File: EmotiBitEda.cpp [hunk 1]
```diff
@@ -386,12 +386,9 @@ bool EmotiBitEda::processData()
 		// NOTE: this can create a small main loop delay
 		// This wouldn't be necessary with a ring buffer
 
-		static const unsigned long int samplingInterval = 1000000 / (_constants.samplingRate * _edrOversampBuffer->capacity());
-#ifdef ADAFRUIT_FEATHER_M0
-		static const unsigned int minSwapTime = max(500, min(samplingInterval / 10, 3500));
-#elif defined ARDUINO_FEATHER_ESP32
-		static const unsigned int minSwapTime = _max(500, _min(samplingInterval / 10, 3500));
-#endif
+		static const int samplingInterval = 1000000 / (_constants.samplingRate * _edrOversampBuffer->capacity());
```
Comment (nitin710) [inline EmotiBitEda.cpp:389]: should this be 
`samplingInterval = (1000000 / _constants.samplingRate) *  _edrOversampBuffer->capacity()` instead?

File: EmotiBit.cpp [hunk 2]
```diff
@@ -1101,10 +1102,10 @@ bool EmotiBit::setupSdCard()
 		Serial.print(i);
 		Serial.print(",");
 		// begin function initializes SPI at MAX speed by deafult. check /src/SpiDriver/SdSpiDriver.h for details on the constructor
-#ifdef ADAFRUIT_FEATHER_M0
-		if (SD.begin(EmotiBitVersionController::SD_CARD_CHIP_SEL_PIN))
-#elif defined ARDUINO_FEATHER_ESP32
+#if defined ARDUINO_FEATHER_ESP32
```
Comment (nitin710) [inline EmotiBit.cpp:1105]: conform to `#ifdef ARDUINO_FEATHER_ESP32`
That seems to be the pattern we are following.

File: EmotiBit.cpp [hunk 3]
```diff
@@ -1125,9 +1126,7 @@ bool EmotiBit::setupSdCard()
 	if (testingMode == TestingMode::ACUTE || testingMode == TestingMode::CHRONIC)
 	{
 		// list all files on SD-Card
-#ifdef ADAFRUIT_FEATHER_M0
-		SD.ls(LS_R);
-#elif defined ARDUINO_FEATHER_ESP32
+#if defined ARDUINO_FEATHER_ESP32
```
Comment (nitin710) [inline EmotiBit.cpp:1129]: conform to `#ifdef ARDUINO_FEATHER_ESP32`
That seems to be the pattern we are following.

File: EmotiBit.cpp [hunk 4]
```diff
@@ -2110,12 +2082,9 @@ bool EmotiBit::processThermopileData()
 	uint32_t timestampAmb;
 	uint32_t timestampSto;
 
-	static const unsigned long int samplingInterval = 1000000 / (_samplingRates.thermopile * _samplesAveraged.thermopile);
-#ifdef ADAFRUIT_FEATHER_M0
-	static const unsigned int minSwapTime = max(500, min(samplingInterval / 10, 10000));
-#elif defined ARDUINO_FEATHER_ESP32
-	static const unsigned int minSwapTime = _max(500, _min(samplingInterval / 10, 10000));
-#endif
+	static const int samplingInterval = 1000000 / (_samplingRates.thermopile * _samplesAveraged.thermopile);
```
Comment (nitin710) [inline EmotiBit.cpp:2085]: Should this be `samplingInterval = (1000000 / _samplingRates.thermopile) * _samplesAveraged.thermopile;`

Otherwise, `samplingInterval` has the dimension sample^2/sec

**Review by nitin710 — COMMENTED** [review]
Pretty standard fixes 👍🏽 
Had a couple of comments about some math stuff. I think it needs to be fixed, unless I misunderstood something.

Also, a few comments about using `#ifdef` vs `#if defined`. Maybe choosing 1 and following that is good practice? but its non-blocking!

File: EmotiBit.cpp (hunk 4 above)
Comment (produceconsumerobot) [reply EmotiBit.cpp:2085]: I think this is incorrect because of the commutativity of multiplication
