### PR TITLE
added bug fix to correct SF sampling rate to events/min

### LINKED ISSUE #193: The value for SF seems to be x2-x3 times expected.
# Description
The SCR frequency, denoted by the type tag `SF` seems to be x2 or x3 times the expected value.

# To recreate
Record data using the FW `v1.3.33` or `v1.3.34`. Count the `SA` occurrences in a given time period. compare the expected value of freq. of SCR occurrence to the value indicated by `SF`

# Bug
There seems to be a math error. The multiplier being used to convert seconds -> minutes is correcting for time period of `SF`, which is already accounted for in the formula.

https://github.com/EmotiBit/EmotiBit_FeatherWing/blob/c1b057ad47a67b620d53924bef54eec50ecc1974/EmotiBitEda.cpp#L651

https://github.com/EmotiBit/EmotiBit_FeatherWing/blob/c1b057ad47a67b620d53924bef54eec50ecc1974/EmotiBitEda.cpp#L746

# Fix
secToMinMultiplier = 60

### PR DESCRIPTION
**Pull request by nitin710**
# Description
- Fixes bug in SF sampling rate.
  - `SF` was being recorded at 3x the events/min(mathematical error)

# Issues referenced
- Fixes #193 

Refer issues for test/results of the fixes applied.

### CODE REVIEW

File: EmotiBitEda.cpp [hunk 1]
```diff
@@ -648,10 +648,9 @@ void EmotiBitEda::processElectrodermalResponse(EmotiBit* emotibit)
 	static const float samplingFrequency = _constants.samplingRate;
 	static const float timePeriod = 1.f / samplingFrequency; // in secs
 	static const float scrFreqTimePeriod = _constants.EDA_SAMPLES_PER_SCR_FREQ_OUTPUT  * timePeriod; // timePeriod of the signal scr:FREQ
-	static const float secToMinMultiplier = 60.f / (scrFreqTimePeriod);  // multiplier used below to convert events/(n secs) -> events/min
 	static DigitalFilter edaLowpassFilter(DigitalFilter::FilterType::IIR_LOWPASS, samplingFrequency, 1); // for bandpassing eda
 	static DigitalFilter edaHighpassFilter(DigitalFilter::FilterType::IIR_HIGHPASS, samplingFrequency, 0.2); // for bandpassing eda
-	static DigitalFilter scrFrequencyFilter(DigitalFilter::FilterType::IIR_LOWPASS, 1.f/(scrFreqTimePeriod), 0.01); // lowPass the calculated scr:FREQ
+	static DigitalFilter scrFrequencyFilter(DigitalFilter::FilterType::IIR_LOWPASS, 1.f/(scrFreqTimePeriod), 1.f/60.f); // lowPass the calculated scr:FREQ
```
Comment (produceconsumerobot) [inline EmotiBitEda.cpp:653]: I thought we discussed using 1/180 to smooth it out more. Why is this 1/60?

**Comment by nitin710** [comment]
# Testing
- Having the filter frequency be 1/180 does not really affect the general shape of the signal. 
- It only controls the height of the peaks and valleys
- Over a long period(80 secs in the image below), it does look very similar
image
